import path from "node:path";
import fs from "node:fs";
import { simpleGit } from "simple-git";
import { getRepos } from "../repos/sqlite/index.js";
import { getOAuthToken } from "../github/oauth.js";
import { parsePlanPatches, applyPatches } from "./patch-applier.js";
import { createPullRequest } from "./pr-creator.js";
import { emitRunLog, emitRunDone } from "./log-emitter.js";
import { PromisePool } from "./promise-pool.js";
import { createPlanWorkspace } from "../lib/workspace-manager.js";

// Pool is created lazily per project to respect configurable concurrency
const pools = new Map<string, PromisePool>();

function getPool(projectId: string): PromisePool {
  let pool = pools.get(projectId);
  if (!pool) {
    const repos = getRepos();
    const project = repos.projects.findById(projectId);
    const concurrency = project?.max_parallel_runs ?? 2;
    pool = new PromisePool(concurrency);
    pools.set(projectId, pool);
  }
  return pool;
}

function log(runId: string, level: "info" | "warn" | "error", message: string, data?: unknown) {
  emitRunLog(runId, { timestamp: new Date().toISOString(), level, message, data });
}

export async function executeRun(runId: string): Promise<void> {
  const repos = getRepos();
  const run = repos.runs.findById(runId);
  if (!run) throw new Error(`Run ${runId} not found`);
  const plan = repos.plans.findById(run.plan_id);
  if (!plan) throw new Error(`Plan ${run.plan_id} not found`);

  const pool = getPool(plan.project_id);
  await pool.run(() => doExecute(runId));
}

async function doExecute(runId: string): Promise<void> {
  const repos = getRepos();
  const run = repos.runs.findById(runId);
  if (!run) throw new Error(`Run ${runId} not found`);

  const plan = repos.plans.findById(run.plan_id);
  if (!plan) throw new Error(`Plan ${run.plan_id} not found`);

  repos.runs.setStarted(runId);
  repos.runs.updateStatus(runId, "RUNNING");
  log(runId, "info", "Run started");

  try {
    const patches = parsePlanPatches(plan.plan_json);
    if (patches.length === 0) {
      log(runId, "warn", "No patches found in plan JSON, nothing to apply");
      repos.runs.updateStatus(runId, "DONE");
      repos.runs.setEnded(runId);
      emitRunDone(runId);
      return;
    }

    // Find target repositories from plan's task or work group
    const targetRepos = getTargetRepos(plan);
    if (targetRepos.length === 0) {
      log(runId, "warn", "No target repositories found");
      repos.runs.updateStatus(runId, "DONE");
      repos.runs.setEnded(runId);
      emitRunDone(runId);
      return;
    }

    // Use plan workspace if available, otherwise create one
    let workspacePath = plan.workspace_path;
    let branchName = plan.branch_name;

    if (!workspacePath || !fs.existsSync(workspacePath)) {
      log(runId, "info", "Creating workspace from local repo copies...");
      const result = await createPlanWorkspace({
        planId: plan.id,
        projectId: plan.project_id,
        repos: targetRepos,
      });
      workspacePath = result.workspacePath;
      branchName = result.branchName;
      repos.plans.update(plan.id, { workspace_path: workspacePath, branch_name: branchName });
    }

    for (const repo of targetRepos) {
      const token = getOAuthToken(plan.project_id);
      if (!token) {
        log(runId, "error", `No GitHub token for project ${plan.project_id}`);
        continue;
      }

      const workDir = path.join(workspacePath, `${repo.owner}_${repo.name}`);
      if (!fs.existsSync(workDir)) {
        log(runId, "warn", `Repo directory not found: ${workDir}`);
        continue;
      }

      const repoGit = simpleGit(workDir);

      // Apply patches
      log(runId, "info", `Applying ${patches.length} patch(es)...`);
      applyPatches(workDir, patches);

      // Commit
      await repoGit.add(".");
      // Use task title for a descriptive commit message
      const task = plan.task_id ? repos.tasks.findById(plan.task_id) : null;
      const commitTitle = task ? task.title : `plan ${plan.id.slice(0, 8)}`;
      const commitMsg = `feat: ${commitTitle}\n\nGenerated by OpenAnt`;
      await repoGit.commit(commitMsg);
      log(runId, "info", "Changes committed");

      // Push
      log(runId, "info", `Pushing branch ${branchName}...`);
      await repoGit.push("origin", branchName!);
      log(runId, "info", "Branch pushed");

      // Create PR
      log(runId, "info", "Creating pull request...");
      try {
        const { prUrl, prNumber } = await createPullRequest({
          projectId: plan.project_id,
          planId: plan.id,
          repositoryId: repo.id,
          repoOwner: repo.owner,
          repoName: repo.name,
          branch: branchName!,
          baseBranch: repo.default_branch,
          title: task ? `[OpenAnt] ${task.title}` : `[OpenAnt] Plan ${plan.id.slice(0, 8)}`,
          body: buildPrBody(plan, task),
        });
        log(runId, "info", `PR #${prNumber} created: ${prUrl}`);
      } catch (err: any) {
        log(runId, "error", `Failed to create PR: ${err.message}`);
      }
    }

    repos.runs.updateStatus(runId, "DONE");
    log(runId, "info", "Run completed successfully");
  } catch (err: any) {
    log(runId, "error", `Run failed: ${err.message}`);
    repos.runs.updateStatus(runId, "FAILED", err.message);
  } finally {
    repos.runs.setEnded(runId);
    emitRunDone(runId);
  }
}

function buildPrBody(
  plan: { id: string; plan_markdown: string | null },
  task: { title: string; description: string | null; requester_count?: number } | null,
): string {
  const lines: string[] = [];
  if (task) {
    lines.push(`## Task`);
    lines.push(`**${task.title}**`);
    if (task.description) lines.push(`\n${task.description}`);
    if (task.requester_count && task.requester_count > 1) {
      lines.push(`\n_Requested by ${task.requester_count} users_`);
    }
  }
  lines.push(`\n---\n🤖 _Generated by [OpenAnt](https://github.com/CristianBB/OpenAnt)_`);
  return lines.join("\n");
}

function getTargetRepos(plan: { project_id: string; task_id: string | null; work_group_id: string | null }) {
  const repos = getRepos();
  // Get all selected repos for the project
  return repos.repositories.listSelectedByProject(plan.project_id);
}
